#!/bin/bash

shopt -s globstar

# directories to omit from deletion for build-caching
OMIT_RM='z3'
# rm -rf z3

CUR=$(pwd)
for f in $(sed -r 's/^.{2}//' <(find . | grep .gitignore)); 
do
	cd "$(dirname $f)"
	while read line;
	do
		rm -rf $(sed -r 's/^.{2}//' <(find . -name "$line"))
	done < <(sed "/^\s*$/d; /^#/d; /$OMIT_RM/d" < .gitignore | uniq | sort)
	cd "$CUR"
done

FORMAT_PYTHON=$(sed -r 's/^.{2}//' <(find . -name '*.py'))
if [[ -n "$FORMAT_PYTHON" ]]; then
	for script in $FORMAT_PYTHON; do
		echo "Formatting: $script"
		autopep8 -j 0 "$script" --in-place
	done
fi
