#!/bin/bash

shopt -s globstar

if [[ -n "${1-}" ]] && [[ -d "$1" ]]; then
	ANTLR_DIR="$1"
else
	ANTLR_DIR='/usr/local/lib'
fi

ANTLR_LOC="$ANTLR_DIR/antlr-4.5-complete.jar"
ANTLR_SYMTAB="$ANTLR_DIR/symtab-1.0.jar"
antlr4="java -jar $ANTLR_LOC"

function check_parser_resource()
{
 	if [ ! -f "$1" ]; then
		curl -O https://raw.githubusercontent.com/g2graman/Z3Parse/master/parser/"$1"
		if [[ -n "${2-}" ]]; then
			$2	
		fi
	fi
}

CD=$(pwd)
if [ ! -f "$ANTLR_LOC" ]; then
	cd "$ANTLR_DIR"
	sudo curl -O http://www.antlr.org/download/antlr-4.5-complete.jar
	cd "$CD"
fi

if [ ! -f "$ANTLR_SYMTAB" ]; then
	cd "$ANTLR_DIR"
	sudo curl -O http://www.antlr.org/download/symtab-1.0.jar
	cd "$CD"
fi

if [[ $(echo "$CLASSPATH" | grep -q "$ANTLR_DIR" && echo "$?") -eq "" ]] && \
	[[ "$(grep $ANTLR_DIR < ~/.bashrc)" == "" ]] && \
	[[ "$(grep $ANTLR_DIR < ~/.profile)" == "" ]]; then


	echo "export CLASSPATH=$CLASSPATH:$ANTLR_DIR:$CD" >> ~/.bashrc
	echo "export CLASSPATH=$CLASSPATH:$ANTLR_DIR:$CD" >> ~/.profile
fi

#CLASSPATH="$ANTLR_LOC:$ANTLR_SYMTAB:$CD/parser"

cd parser
check_parser_resource main.py '$antlr4 -Dlanguage=Python2 Z3proof.g4 -Werror'
check_parser_resource main.py
check_parser_resource Z3proofFormatter.py

REBUILD=$(sed -r 's/^.{2}//' <(find . -maxdepth 1 -name '*.py') | grep -v Z3proofFormatter.py | grep Z3proof)
if [[ -z "$REBUILD" ]]; then
	$antlr4 -Dlanguage=Python2 Z3proof.g4 -Werror # generate parser
fi

cd ..
