#!/bin/bash

shopt -s globstar

Z3_BUILD_DIR='z3/build'
CURRENT=$(pwd)

main='get_proof.py'
to_copy=$(ls src/*.py)

cp $to_copy "$Z3_BUILD_DIR"/
cd "$Z3_BUILD_DIR"
python "$main"

for f in $to_copy; do
	rm -rf "${Z3_BUILD_DIR:?}/$(basename $f)"
done
cd "$CURRENT"
