#!/bin/bash

# $1 may contain name of python file to run with z3 resources
Z3_BUILD_DIR='z3/build'
ERR=0
CURRENT="`pwd`"

if [[ -n "${1-}" ]] && [ -f $1 ]; then
	file="$(basename $1)"
	cp "$1" "$Z3_BUILD_DIR"/"$file"
	cd "$Z3_BUILD_DIR"
	python "$file"
	ERR=$?
	rm -f "$Z3_BUILD_DIR"/"$file"
	cd $CURRENT
fi 

exit $ERR
